### ISSUE TITLE
The error of the website of CASCADE

### ISSUE THREAD

**Issue by Jingxian-Ren** [patonlab/CASCADE#4]
First of all, thank you for the development of this strong tool for chemical shift prediction. But recently, the website of "http://nova.chem.colostate.edu/cascade/" showed error of 404 NOT FOUND (nginx/1.14.1). Can I trouble you to maintain the website？ Thanks so much.

**Comment by shreesowndarya** [comment]
Hello,

We have fixed the webpage. Do take a look and let us know if you have any more issues! Thanks for letting us know that it wasn't working.
